<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://venus.sod.asu.edu/WSRepository/xml" targetNamespace="http://venus.sod.asu.edu/WSRepository/xml" 
elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="Hotels" type="HotelsInfo"/>
    <xs:complexType name="HotelsInfo">
        <xs:sequence>
            <xs:element name="Hotel" type="HotelInfo" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    </xs:complexType>
    <xs:complexType name="HotelInfo">
<xs:sequence>
<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
<xs:element name="Phone" type="PhoneType" minOccurs="1" maxOccurs="unbounded"/>
<xs:element name="Address" type="AddressDetails" minOccurs="1" maxOccurs="1"/>
</xs:sequence>
<xs:attribute name="Rating" type="xs:string" use="optional"/>
</xs:complexType>
<xs:simpleType name="PhoneType">
<xs:restriction base="xs:string">
<xs:pattern value="\d{3}\-\d{3} \d{4}"/>
</xs:restriction>
</xs:simpleType>
<xs:complexType name="AddressDetails">
<xs:sequence>
<xs:element name="Number" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>
<xs:element name="Street" type="xs:string" minOccurs="1" maxOccurs="1"/>
<xs:element name="City" type="xs:string" minOccurs="1" maxOccurs="1"/>
<xs:element name="State" type="xs:string" minOccurs="1" maxOccurs="1"/>
<xs:element name="Zip" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>
</xs:sequence>
<xs:attribute name="NearestAirport" type="xs:string" use="required"/>
</xs:complexType>
</xs:schema>
